spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC
      username: root
      password: admin
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000

  thymeleaf:
    cache: false
  messages:
    basename: i18n.login
  mvc:
    format:
      date: yyyy-MM-dd
    # put请求，delete请求
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  type-aliases-package: com.zhao.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8081

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
